### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by anbai106** [ejolly/pymer4#92] opened 2021-11-13 18:44 UTC
Hi, 

I got this error:
```

  File "/home/hao/Project/sopNMF_atlas/scripts/tasks/IWAS_ICD10/2_IWAS_analysis_UKBB_ICD.py", line 100, in lm_pvalue
    results = model_all.fit(n_jobs=8)
  File "/home/hao/Software/Anaconda3/envs/sopNMF_atlas_3.8/lib/python3.8/site-packages/pymer4/models/Lm.py", line 405, in fit
    self.rsquared_adj = rsquared_adj(
  File "/home/hao/Software/Anaconda3/envs/sopNMF_atlas_3.8/lib/python3.8/site-packages/pymer4/stats.py", line 647, in rsquared_adj
    return 1.0 - (nobs - 1) / df_res * (1.0 - r)
ZeroDivisionError: division by zero
```

Any clues regarding this?

**Comment by ejolly** [comment] 2021-11-13 21:18
Hey @anbai106 thanks for noting this issue. It looks two things were going on here, one of which was related to how `pymer4` handles _square matrices_ for regression estimation. I pushed a fix in the dev branch which should be up on the `pre-release` conda channel for pymer4 later today after the test suite passes. You can install that version by following the [instructions for install a development release](https://eshinjolly.com/pymer4/installation.html#for-the-latest-development-release). Or if you already have the other pymer4 dependencies setup in an existing conda environment you can install `pymer4` from the master branch on github using `pip install git+https://github.com/ejolly/pymer4.git`

A bit of explanation for issue 1, both for context and as a reminder to my future self :) 

In the rare case a model has exactly the same number of predictors as observations, degrees-of-freedom calculation could be 0 so it's not possible to compute an adjusted R^2 using the standard formula, hence the error you see. I fixed that by guarding against that situation when calculating adjusted R^2, as well as making the dof calculating a bit more robust using `np.linalg.matrix_rank` rather than `x.shape[0] - x.shape[1]` like `statsmodels` does. It's rare to encounter this unless you're using some kind of saturated model, which leads me to issue two on your end:

The second issue is related to your model specification  **which you should double-check**. Without knowing your model formula and the data you're working with, there's no way for me to tell what the __exact__ issue is. And handling specific user model issues are a bit beyond the scope of addressing issues with `pymer4` itself. BUT, my best guess is that  It seems as though one of several possible things could be going on that landed you in a sort of "edge-case" scenario:

- You have the same number (or more) predictors in your model than you have observations
- Or some of your predictors are perfectly correlated with each other or with the dependent variable leading to some degeneracy in the model and/or unintended perfect predictability of the dependent variable 
- Or you've done some mean-centering but are still including a model intercept. You can skip intercept estimation by following the patsy formula language e.g. `DV ~ 0 + IV1 + ...`. 
- Even if the fix I pushed ended up working for you, you should be a bit cautious interpreting the results and make sure the model is estimating what you want

I'm going to close this for now, but feel free to re-open if you feel like there's still some kind of technical issue happening with `pymer4`. 

Hope that helps!

**Closed by ejolly** 2021-11-13 21:18 UTC
Labels: bug

**Comment by anbai106** [comment] 2021-11-14 12:55
Your speculations were correct! I do have less N than the number of covariates!

Thanks
