### ISSUE TITLE
Install issue not covered in installation page

### ISSUE THREAD

**Issue by Beeskey** [ejolly/pymer4#50] opened 2019-11-07 05:18 UTC
I'm running into an issue when trying to an issue when checking my install of pymer4. Below is the output of the line: python -c "from pymer4.test_install import test_install; test_install()"
![Screen Shot 2019-11-06 at 6 39 38 PM](https://user-images.githubusercontent.com/25391589/68362076-fb379c00-00f3-11ea-9120-53e29ef77d27.png)

I went through the entire installation guide, from installing Anaconda all the way through the issues section with no errors or issues so far as I can tell. Please let me know what other info is needed!
Also, great work on the package! I hope I can get it working :)

**Comment by ejolly** [comment] 2019-11-07 21:32
Hmm so this looks like an issue in which `rpy2` cannot find parts your R installation. Did you have an existing R installation on your system or did you install R for the first time using Anaconda? Having two separate R installations can cause issues like the one you're encountering.

What happens when you just try to launch R in a new terminal (i.e. opening a new terminal and just typing `R`)? And what about if you try to import an R package from within R, e.g. `library(lme4)` after launching R ?

**Comment by Beeskey** [comment] 2019-11-08 06:53
Eshin,

Thanks so much for the response! So, I actually was able to solve the
issue. It seems silly, but I'm a Python user, and non of the searching I
did brought up any suggestions to *install Matrix! *After I did that and
restarted R, running test_install came back positive!!!!

I'm very sorry to go through the trouble of making a ticket for what ended
up being an issue with the R installation. To perhaps help in any future
cases, here's what I did:

I followed your installation guide, and installed Anaconda before
beginning. From there, I entered in terminal to install R-base and the
three additional packages. I did not have an existing R installation. I was
able to install Pymer4, but when I proceeded to the final step to run the
test_install, I would get the error that follows:







*Loading required package: MatrixError: package or namespace load failed
for ‘Matrix’ in dyn.load(file, DLLpath = DLLpath, ...): unable to load
shared object '/opt/anaconda3/lib/R/library/Matrix/libs/Matrix.dylib':
dlopen(/opt/anaconda3/lib/R/library/Matrix/libs/Matrix.dylib, 6): Library
not loaded: @rpath/libopenblas.0.dylib  Referenced from:
/opt/anaconda3/lib/R/library/Matrix/libs/Matrix.dylib  Reason: image not
foundError: package ‘Matrix’ could not be loaded*

From there, I went all the way through the "Installation Issues" tutorial
of the page but to no avail. It took coming back after a day rest and your
email's checks to find a very simply solution. I'm just curious how/why
Matrix didn't get installed when I installed R. Really confusing.

Again, thank you for your help and for creating this package! can't wait to
use it. Should I go back to the Github and delete the ticket?

Cheers,
Reed

**Comment by ejolly** [comment] 2019-11-08 07:08
Not silly at all and no need to apologize. Most of the issues I've dealt with regarding my package have centered around R installation issues actually. I think the nature of what this package tries to do, i.e. being an inter-language operability packaging is inherently challenging and it's hard to anticipate all the different setups that users have with R and Python on their systems as well as issue (like yours) that unexpectedly arise when Anaconda behaves strangely. 

Did you end up installing Matrix through R directly e.g. `install.packages(c(Matrix))` or using Anaconda, e.g. (not sure of the exact name but something like) `conda install r-matrix`? Just asking cause what I can do is add another note to the installation issues section of the documentation so your struggles aren't in vain and can be valuable for future folks!

**Comment by Beeskey** [comment] 2019-11-08 18:36
I was hoping my experience could help future users! I ended up installing
Matrix through R, though this was the line I used:
> install.packages("Matrix", repos="http://R-Forge.R-project.org")

Still so new to R, I basically just searched Google for "how do I install
Matrix" so, I don't know if I found the proper format or not haha.
Thanks for your support! Very excited to use to package, great work!

**Comment by Beeskey** [comment] 2019-11-08 21:47
Quick question: Can I supply "binomial" for the family argument and fit a
non-linear model? I didn't see any mention of it, but it takes the family
argument, which makes me wonder if it's possible.

Thank you for your help

**Comment by ejolly** [comment] 2019-11-09 02:25
Great thanks for the info. I've added a note in the installation section of the docs.

And yup, all `Lmer` models support the `family` argument with the available options being: gaussian (default), binomial, gamma, inverse_gamma, and possion. You can check out details at the API documentation here: http://eshinjolly.com/pymer4/api.html

Currently `Lm` and `Lm2` models don't support anything except regular linear model (i.e. no family argument).

Going to close this issue for now

**Closed by ejolly** 2019-11-09 02:25 UTC

**Comment by Beeskey** [comment] 2019-11-11 01:22
Eshin,

Thanks for the response! I was finally able to get a model to work! Thank
you for the help.

I do have another question, however, and didn't know if I should create an
issue ticket or just ask in email. If it turns out to be a true bug and not
just my own user error, I'd be more than happy to create a ticket.

What's happening is, when I use the model.predict() function, I'm getting
an array the same length as my training data set, not my test data set (I'm
using an 80-20 train and test split). Here's an example:
[image: Screen Shot 2019-11-10 at 8.21.14 PM.png]

Am I using the predict() function incorrectly? I would appreciate any help
you can offer!

Best regards,
Reed

**Comment by ejolly** [comment] 2019-11-11 01:38
Not quite sure what's happening (your picture didn't come through), but I'm reasonably certain it's not a bug. Here's an example that returns the corrected expected data shapes using the sample data in `pymer4`, testing both `Lmer` and `Lm` models:

```
# Imports
from pymer4.models import Lmer, Lm
from pymer4.utils import get_resource_path
import os
import pandas as pd

# Load sample data and split into different sizes
data = os.path.join(get_resource_path(), 'sample_data.csv')
df = pd.read_csv(data)
df_train = df.query("Group < 30").reset_index(drop=True)
df_test = df.query("Group > 30").reset_index(drop=True)

# Print sizes
print(df_train.shape)
print(df_test.shape)

# Fit lmm and make sure predictions are the right size
m = Lmer("DV  ~ IV2 + (1|Group)",data=df_train)
m.fit(summarize=False)
preds = m.predict(df_test)
assert preds.shape[0] == df_test.shape[0]
print(preds.shape)

# Fit lm and make sure predictions are the right size
m = Lm("DV  ~ IV2",data=df_train)
m.fit(summarize=False)
preds = m.predict(df_test)
assert preds.shape[0] == df_test.shape[0]
print(preds.shape)
```

**Comment by Beeskey** [comment] 2019-11-11 03:58
Oh, I'm sorry the embedded picture didn't work. Thanks for the response and
example.
I've restarted my kernel and am rerunning my whole notebook now to see if
that helps. I'll attach the picture to see if it's informative at all, but
it looks pretty much exactly like your example, I believe. I'll keep you
posted if the issue persists.

Thank you for your support,
Reed

**Comment by Beeskey** [comment] 2019-11-11 23:29
Hey Eshin,

*Unfortunately I'm still having the issue. It's odd...I've never seen an
issue like this. Here is my instantiation and fit:*
model = Lmer('TYPE ~ STATE + AGE + SEX + MONTH + YEAR + CLUSTER +
(1|STATE)', data=flu_train, family='binomial')
model.fit()

*here's my predict call (The data set here is a dummy coded version of the
test set from the same data as the above):*
XD_test = XD_test.applymap(str)
y_pred = model.predict(XD_test[list(model.design_matrix.columns[1:])])

*And a few test prints:*

shape of data going into model.predict: (135807, 47)
shape of model.predict output, y_pred: (543225,)
flu_train_shape: (543225, 8)
XD_test_shape: (135807, 57)

If you have any tips, I would greatly appreciate it. If you want more
details or anything, I can try to provide more. Could it have to do with
using a non-dummy-coded training set? Thanks for your help,
Reed

**Comment by ejolly** [comment] 2019-11-12 01:55
Hmm, this looks like something specific with your data and not an issue with pymer4. So, unfortunately don't think I can be much help.

 I'd encourage you to check out the [lme4 documentation](https://cran.r-project.org/web/packages/lme4/index.html), which is the R package that this package calls behind the scenes for mixed modeling. Models called with predict need to contain the *same* predictors as models that are estimated so it's possible you're having an issue with the dummy coding. You can check out how the predict function behaves in lme4 [here](https://www.rdocumentation.org/packages/lme4/versions/1.1-21/topics/predict.merMod). 

More generally the [cross validated stackoverflow site](https://stats.stackexchange.com/) is a better place to get help with the kind of issue you're having rather than here on github, which is better suited for package-specific bugs, features, etc. Plus there you'll be able to leverage the knowledge/experience of a much larger community!  

Since the original issue has been solved I've closed it here on github and will close this thread. Of course, if you find other bugs, etc feel free to open another issue.
