### ISSUE TITLE
Names of fixed effects for fitted_model.anova()

### ISSUE THREAD

**Issue by simonruch** [ejolly/pymer4#103] opened 2022-03-21 15:22 UTC
The data frame that is returend by the  ".anova()" function for Lmer-objects does not include the names of the fixed effects that are reported. Would it be possible to parse these from the r-object? I could not figure out how this would be achieved.

See e.g. the example by the Pymer-Tutorial 3.:
http://eshinjolly.com/pymer4/auto_examples/example_03_posthoc.html#sphx-glr-auto-examples-example-03-posthoc-py

```
 SS Type III Analysis of Variance Table with Satterthwaite approximated degrees of freedom:
 (NOTE: Using original model contrasts, orthogonality not guaranteed)
             SS           MS  NumDF  DenomDF    F-stat     P-val Sig
 0  2359.778135  1179.889067      2    515.0  5.296284  0.005287  **
```

The data frame returned by model.anova(force_orthogonal=True) contains only the numeric index (0), but not the name ("IV3") of the factor.
With complex models (e.g. full model with 3 predictors including all main effects and all possible interaction terms), interpretation of the output becomes very complicated. I am assumign that the output is A, B, C, AxB, AxC, BxC, AxBxC if the model was specified as such ...

**Comment by ejolly** [comment] 2022-03-29 18:26
Duplicate of #88

**Closed** 2022-09-24 05:00 UTC
Labels: bug, duplicate
