### ISSUE TITLE
rpy2>3.2.4 returns empty random effects

### ISSUE THREAD

**Issue by Jorsorokin** [ejolly/pymer4#57] opened 2020-04-21 02:03 UTC
Hello, I've been using `pymer4` for a few months now but only recently encountered this issue:
the `Lmer` module seems to be returning empty random effects variances. Not sure if this is due to R/rpy2/pymer4/pandas version incompatibility (3.6.3, 3.3.1, 0.7.0, 1.0.0, respectively) but even this simple example fails:
```python
import seaborn as sns
import pymer4

data = sns.load_dataset('mpg')
model = pymer4.Lmer('mpg ~ weight + (1 | origin)', data)
model.fit()
```

**Comment by ejolly** [comment] 2020-04-22 06:27
Hmm that's very strange because I can't seem to be able to reproduce any issues running your example (output below). I'm guessing you're right about some new incompatibilities and my hunch is that it's going from `pandas 0.25.x` -> `1.0.0`, since `1.0.x` introduced a reasonable number of breaking changes.  

Any chance you can downgrade pandas and see if that solves the issue and if it doesn't paste any output you get when you run the code (e.g. errors, warnings)? Not recommending that as a long term fix, but it would help pinpoint the issue. Can you also provide version information for `lme4` and `lmerTest`? I'm hoping it's not a breaking change from an R package because that's a bit more challenging to debug and fix. 

With R/rpy2/pymer4/pandas at (3.6.2/3.2.4/0.7.0/**0.25.3**) running your snippet yields the expected output:

```
Formula: mpg~weight+(1|origin)

Family: gaussian	 Inference: parametric

Number of observations: 398	 Groups: {'origin': 3.0}

Log-likelihood: -1152.812 	 AIC: 2305.623

Random effects:

                 Name     Var    Std
origin    (Intercept)   1.178  1.086
Residual               18.373  4.286

No random effect correlations specified

Fixed effects:

Out[5]:
             Estimate  2.5_ci  97.5_ci     SE       DF  T-stat  P-val  Sig
(Intercept)    45.104  43.000   47.208  1.074   10.919  42.012    0.0  ***
weight         -0.007  -0.008   -0.007  0.000  254.887 -23.001    0.0  ***
```

Also `model.ranef` returns:

```
        (Intercept)
europe     0.038227
japan      0.974448
usa       -1.012675
```

While `model.fixef` returns:

```
        (Intercept)    weight
europe    45.142006 -0.007122
japan     46.078228 -0.007122
usa       44.091104 -0.007122
```

**Comment by Jorsorokin** [comment] 2020-04-22 15:39
Looks like pandas 0.25.3 does not solve the issue for me, suggesting it might be an lme4/lmerTest version issue. Which versions of these packages do you have installed?

**Comment by ejolly** [comment] 2020-04-22 17:16
Interesting, so models aren't being miscomputed just `pymer4` isn't grabbing the proper outputs from lme4. The versions I have are `lmer4=1.1-21` and `lmerTest=3.1-1`, which only seem minor versions behind the latest releases making me think that couldn't have changed _that_ much. Another (frustrating) possibility is that changes to `rpy2` are not coercing the R types to Python in the same way in newer versions. Many of previous issues in `pymer4` were often due to breaking changes in even minor updates to `rpy2`. 

If you're able to retry using `rpy2==3.2.4` and see if that solves the issue I can try to figure out what's changed. Otherwise I'll need to look a bit deeper on the R side of things

**Comment by Jorsorokin** [comment] 2020-04-22 17:48
ah! that was it!

**Comment by ejolly** [comment] 2020-04-22 17:55
Great! Thanks for trying out the different package versions to diagnose. I'm going relabel this issue as a necessary fix for a future release of `pymer4`

**Comment by ejolly** [comment] 2020-04-26 17:08
Adding some error information here from another user who experienced a similar issues with `rpy2 >= 3.3.x`  

```
**python3.7/site-packages/pymer4/models/Lmer.py in <module>
     21 
     22 # Make a reference to the default R console writer from rpy2
---> 23 consolewrite_warning_backup = rinterface_lib.callbacks.consolewrite_warnerror
     24 consolewrite_print_backup = rinterface_lib.callbacks.consolewrite_print
     25 
AttributeError: module 'rpy2.rinterface_lib' has no attribute 'callbacks'**
```

**Comment by ejolly** [comment] 2020-07-07 17:09
Should be fixed in https://github.com/ejolly/pymer4/commit/a254059c0e8fa59cfba9eeb8c42dca078d2cde14

**Closed by ejolly** 2020-07-07 17:09 UTC
Labels: bug, future fix
